Module 3 with errors
1) Hero, Sales Banner, & Categories
       `main.css` should contain a `.hero` class @hero-section:
     AssertionError: It seems that you are missing a rule with a selector like `.hero`, or you are missing key declarations in that rule.
      at Context.<anonymous> (test/unit/module3.test.js:11:5)
      at processImmediate (node:internal/timers:463:21)

  2) Hero, Sales Banner, & Categories
       `main.css` should contain rules with the selectors, `.hero h1, .hero h2`, `.hero h1`, and `.hero h2` @hero-headings:
     AssertionError: It seems that you are missing a rule with a selector like `.hero h1, .hero h2`, or you are missing key declarations in that rule.
      at Context.<anonymous> (test/unit/module3.test.js:15:5)
      at processImmediate (node:internal/timers:463:21)

  3) Hero, Sales Banner, & Categories
       `main.css` should contain a `.hero` class, it should be used in `index.html` @hero-class-attribute:
     AssertionError: The `.hero` class should exist before it can be used in the HTML.
      at Context.<anonymous> (test/unit/module3.test.js:25:5)
      at processImmediate (node:internal/timers:463:21)

  4) Hero, Sales Banner, & Categories
       `main.css` should contain a rule with a selector of `.hero` @banner-text-last-child:
     AssertionError: It seems that you are missing a rule with a selector like `.banner-text > div:last-child`, or you are missing key declarations in that rule.
      at Context.<anonymous> (test/unit/module3.test.js:39:5)
      at processImmediate (node:internal/timers:463:21)

  5) Hero, Sales Banner, & Categories
       `main.css` should contain a rule with a selector of `.hero p`  @category-text-divs:
     AssertionError: It seems that you are missing a rule with a selector of .category-text > div.
      at Context.<anonymous> (test/unit/module3.test.js:58:5)
      at processImmediate (node:internal/timers:463:21)