module 5 with errors
  1) Footer
       `main.css` should contain a rule with a selector of `footer` @footer:
     AssertionError: It seems that you are missing a rule with a selector like `footer`, or you are missing key declarations in that rule.
      at Context.<anonymous> (test/unit/module5.test.js:13:5)
      at processImmediate (node:internal/timers:463:21)

  2) Footer
       `main.css` should contain a rule with a selector of `footer:after` @footer-sidebar:
     AssertionError: It seems that you are missing a rule with a selector like `footer:after`, or you are missing key declarations in that rule.
      at Context.<anonymous> (test/unit/module5.test.js:17:5)
      at processImmediate (node:internal/timers:463:21)

  3) Footer
       `main.css` should contain a `.lists` class @lists:
     AssertionError: It seems that you are missing a rule with a selector like `.lists`, or you are missing key declarations in that rule.
      at Context.<anonymous> (test/unit/module5.test.js:21:5)
      at processImmediate (node:internal/timers:463:21)

  4) Footer
       `main.css` should contain rules with the selectors, `footer a`, and `footer a:hover` @links:
     AssertionError: It seems that you are missing a rule with a selector like `footer a`, or you are missing key declarations in that rule.
      at Context.<anonymous> (test/unit/module5.test.js:29:5)
      at processImmediate (node:internal/timers:463:21)

  5) Footer
       `main.css` should contain the classes, `.lists`, and `.link-header`, they should be used in `index.html` @link-class-attributes:
     AssertionError: The `.lists` class should exist before it can be used in the HTML.
      at Context.<anonymous> (test/unit/module5.test.js:34:5)
      at processImmediate (node:internal/timers:463:21)